// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbeh7XV9dhSC8g1FASkr7BAhHHxHn0NxA',
    appId: '1:63624510980:web:aaab234ee2fef70452bf51',
    messagingSenderId: '63624510980',
    projectId: 'flutter-instagram-clone-9556e',
    authDomain: 'flutter-instagram-clone-9556e.firebaseapp.com',
    storageBucket: 'flutter-instagram-clone-9556e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsfK0vcU9izim7JdHNoRvYLjcKpPEH2sc',
    appId: '1:63624510980:android:412540f050c8351552bf51',
    messagingSenderId: '63624510980',
    projectId: 'flutter-instagram-clone-9556e',
    storageBucket: 'flutter-instagram-clone-9556e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnhGNpwymFLO6fsFdE7paBrIv-wz_0sww',
    appId: '1:63624510980:ios:86f3fbbcdf51599052bf51',
    messagingSenderId: '63624510980',
    projectId: 'flutter-instagram-clone-9556e',
    storageBucket: 'flutter-instagram-clone-9556e.appspot.com',
    iosBundleId: 'com.example.instagramClone',
  );
}
